control_dt: 0.02
arm_lp_filter_alpha: 0.4
hand_lp_filter_alpha: 0.5
moveit:
  namespace: 'followers'
  arm_group_name: 'arm1'
  hand_group_name: ''
  num_planning_attempts: 30
  planning_time: 20.0
  max_velocity_scaling_factor: 0.1
  max_acceleration_scaling_factor: 0.1
  use_move_group_action: True
robots:
  robot1:
    arm_control_topic: '/arm1_controller/joint_trajectory'
    arm_control_msg_type: 'JointTrajectory'
    hand_control_topic: '/gripper1_controller/joint_trajectory'
    hand_control_msg_type: 'JointTrajectory'
    # These joint names need to match the order of the joints for publishing commands
    arm_joint_names: ['robot1/joint1', 'robot1/joint2', 'robot1/joint3', 'robot1/joint4', 'robot1/joint5', 'robot1/joint6', 'robot1/joint7']
    hand_joint_names: ['robot1/gripper']
    arm_state_sub_topic: '/joint_states'
    hand_state_sub_topic: '/joint_states'
    arm_state_sub_msg_type: 'JointState'
    hand_state_sub_msg_type: 'JointState'
cameras: null
#  top:
#    serial_number: 'f0171772'
#    rgb_resolution: [640, 360]
#    depth_resolution: [640, 480]
#    get_aligned: true
#    depth_units: 0.0002500000118743628
#  right:
#    serial_number: '130322274055'#'102422071302'
#    rgb_resolution: [480, 270]
#    depth_resolution: [480, 270]
#    get_aligned: false
#    depth_units: 9.999999747378752e-05
#  left:
#    serial_number: '218722271580'#'103422071304'
#    rgb_resolution: [480, 270]
#    depth_resolution: [480, 270]
#    get_aligned: false
#    depth_units: 9.999999747378752e-05
#  top:
#    serial_number: '238722071363'
#    rgb_resolution: [848, 480]
#    depth_resolution: [848, 480]
#  right:
#    serial_number: '130322274055'#'102422071302'
#    rgb_resolution: [480, 270]
#    depth_resolution: [480, 270]
#  left:
#    serial_number: '218722271580'#'103422071304'
#    rgb_resolution: [480, 270]
#    depth_resolution: [480, 270]

